<a href="https://colab.research.google.com/github/Dummy-Bug/Machine-Learning/blob/master/Saving_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating A Model

---
DATA USED : - 
```
area,price
2600,550000
3000,565000
3200,610000
3600,680000
4000,725000
```

In [ ]:
# loading dependencies
import pandas as pd
import numpy as np
from sklearn import linear_model
print("Modules Loaded Sucessfully")

Modules Loaded Sucessfully


In [ ]:
# loading our data
df = pd.read_csv('/content/train.csv')

# viewing few files
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [ ]:
# creating the model object
model = linear_model.LinearRegression() # y = mx+b

# fitting model with X_train - area, y_train - price
model.fit(df[['area']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
# checking coeffiecent - m
model.coef_

array([135.78767123])

In [ ]:
# checking intercept - b
model.intercept_

180616.43835616432

In [ ]:
# predict model values - area = 5000
model.predict([[5000]]) 

array([859554.79452055])

# Saving A Model

## Using Pickel

- Helps in deserialization of a python object i.e breaking down an object into its constituting components.
- The pickle module keeps track of the objects it has already serialized, so that later references to the same object won’t be serialized again, thus allowing for faster execution time 
- Allows to save model in very less time
- Good For small models with less parameters 

In [ ]:
# loading library
import pickle

In [ ]:
# create an iterator object with write permission - model.pickle
with open('model_pkl', 'wb') as files:
    pickle.dump(model, files)

- We opened a new file - `with open('model_pkl', 'wb')` where `wb` stands for write binary file and aliased as `files`
- then we saved our `model` objects in `files` using `pickle.dump(object = None , filename)` method

After this one can se `model_pkl` in dir

In [ ]:
# load saved model
with open('model_pkl' , 'rb') as f:
    lr = pickle.load(f)

- We opened create file `model_pkl` and gave read only permission under alias name `f`
- Next we saved our loded file in variable name `lr` using `pickle.load(filename=None)`

After this one can use model using `lr` 

In [ ]:
# check prediction
lr.predict([[5000]]) # similar

array([859554.79452055])

## Sklearn Joblib

- Usefull in saving model but requires `` dependency
- Very good for large model which have many parameters and can have large numpy arrays in backend
- Can only save file to disk and not to a string as opposed to `pickle`
- Works similar to pickle `dump` and `load`
- Most fitted for estimators

In [ ]:
# loading dependecy
from sklearn.externals import joblib

In [ ]:
# saving our model
joblib.dump(model , 'model_jlib')

['model_jlib']

- Similar to pickle we used `joblib.dump(obj, name)` method to save model
-- model: **model**
-- name : **model_jlib**

In [ ]:
# opening the file
m_jlib = joblib.load('model_jlib')

- We Loaded file using `joblib.load(name)` method using m_jlib

In [ ]:
m_jlib.predict([[5000]]) # similar

array([859554.79452055])